#!/bin/bash

function help {
    echo 'Usage: make-drupal-links -d [DIRECTORY] -v [DRUPAL MAJOR VERSION NUMBER]'
    echo 'Make links to create a site within a multi-site Drupal installation.'
    echo ''
    echo 'These are mandatory arguments.'
    echo '  -d directory'
    echo '  -v major Drupal version number (6, 7, etc.)'
    echo ''
}    

if [ -z $1 ]; then
    help
    exit 1
fi

while getopts "d:v:" opt; do
    case $opt in
	d)
	    dir=$OPTARG
	    ;;
	v)
	    v=$OPTARG
	    ;;
	*)
	    help
	    exit 1
	    ;;
    esac
done

d=`dirname $dir`
s=`basename $dir`

mkdir -p $d/$s/sites/all
mkdir -p $d/$s/sites/$s
cd $d/$s
ln -s ../drupal/drupal$v/.htaccess
ln -s ../drupal/drupal$v/cron.php
ln -s ../drupal/drupal$v/install.php
ln -s ../drupal/drupal$v/update.php
ln -s ../drupal/drupal$v/misc
ln -s ../drupal/drupal$v/modules
ln -s ../drupal/drupal$v/profiles
ln -s ../drupal/drupal$v/scripts
ln -s ../drupal/drupal$v/themes
cd $d/$s/sites
ln -s ../../drupal/drupal$v/sites/default